# Databricks Asset Bundle Configuration
bundle:
  name: ecowind_energy

# Storage Configuration
storage:
  account: your_storage_account  # Replace with actual storage account
  container: dbx
  paths:
    landing: 1-Landing
    bronze: 2-Bronze
    silver: 3-Silver

# Unity Catalog Configuration
catalog:
  name: dev_ecowind
  schema: turbines
  tables:
    bronze: turbinestats_bronze
    silver: turbinestats_silver

# Data Quality Configuration
data_quality:
  max_missing_percentage: 5
  power_output_range:
    min: 0
    max: 100
  wind_speed_range:
    min: 0
    max: 100

# Pipeline Configurations
pipelines:
pipelines:
  bronze:
    name: bronze_dlt_pipeline
    catalog: ${var.environment}
    target: ${workspace.current_user.short_name}_bronze
    libraries:
      - notebook:
          path: ${workspace.root_path}/files/src/dlt_patterns/table_creation/orchestrator
    permissions:
      - user_name: ${workspace.current_user.userName}
        level: CAN_MANAGE
    clusters:
      - node_type_id: Standard_F4
        autoscale:
          min_workers: 1
          max_workers: 1
    configuration:
      bundle.sourcePath: ${workspace.file_path}/src/
      environment: ${var.environment}
      root_path: ${workspace.root_path}
      layer: bronze
      user_short_name: ${workspace.current_user.short_name} Time window for statistics calculation 